/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pruebaproyectofinal;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author nightlyhorny
 */
public class Login extends javax.swing.JFrame {
    int xMouse, yMouse;

    /** Creates new form Inicio */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSexo = new javax.swing.ButtonGroup();
        mesesrel = new javax.swing.ButtonGroup();
        Bg = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        LblRelaciones = new javax.swing.JLabel();
        TxtEdad = new javax.swing.JTextField();
        LblEdad = new javax.swing.JLabel();
        RBtnHombre = new javax.swing.JRadioButton();
        RBtnMujer = new javax.swing.JRadioButton();
        BtnIngresar = new javax.swing.JButton();
        LblSexo = new javax.swing.JLabel();
        RBtnNo = new javax.swing.JRadioButton();
        RBtnSi = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        Bg.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Biblioteca de ETS");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 228, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/icons8-hospital-100.png"))); // NOI18N
        Bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Biblioteca de ETS");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("by Ian Roberto Tejada Reyes (NightlyHorny)");
        Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/city.png"))); // NOI18N
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("esta no sera compartida con nadie.");
        Bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Por favor ingresa la siguiente informacion para continuar");
        Bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        LblNombre.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        LblNombre.setText("Nombre:");
        Bg.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        TxtUser.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        TxtUser.setForeground(new java.awt.Color(153, 153, 153));
        TxtUser.setText("Ingresa tu nombre");
        TxtUser.setBorder(null);
        TxtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtUserFocusLost(evt);
            }
        });
        TxtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtUserMousePressed(evt);
            }
        });
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        Bg.add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 410, -1));

        LblRelaciones.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        LblRelaciones.setText("Has tenido relaciones los ultimos meses:");
        Bg.add(LblRelaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        TxtEdad.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        TxtEdad.setForeground(new java.awt.Color(153, 153, 153));
        TxtEdad.setText("Ingresa tu edad");
        TxtEdad.setBorder(null);
        TxtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtEdadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtEdadFocusLost(evt);
            }
        });
        TxtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtEdadMousePressed(evt);
            }
        });
        TxtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEdadActionPerformed(evt);
            }
        });
        TxtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEdadKeyTyped(evt);
            }
        });
        Bg.add(TxtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 420, -1));

        LblEdad.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        LblEdad.setText("Edad:");
        Bg.add(LblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        GrupoSexo.add(RBtnHombre);
        RBtnHombre.setText("Hombre");
        RBtnHombre.setBorder(null);
        RBtnHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnHombreActionPerformed(evt);
            }
        });
        Bg.add(RBtnHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        GrupoSexo.add(RBtnMujer);
        RBtnMujer.setText("Mujer");
        RBtnMujer.setBorder(null);
        Bg.add(RBtnMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        BtnIngresar.setBackground(new java.awt.Color(0, 102, 153));
        BtnIngresar.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setBorder(null);
        BtnIngresar.setBorderPainted(false);
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseExited(evt);
            }
        });
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        Bg.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 80, 30));

        LblSexo.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        LblSexo.setText("Sexo:");
        Bg.add(LblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        mesesrel.add(RBtnNo);
        RBtnNo.setText("No");
        Bg.add(RBtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        mesesrel.add(RBtnSi);
        RBtnSi.setText("Si");
        Bg.add(RBtnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel9.setText("INGRESAR");
        Bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 410, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        Bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 410, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed

            
          
        
    }//GEN-LAST:event_TxtUserActionPerformed

    private void TxtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEdadActionPerformed

    private void RBtnHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtnHombreActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        txtExit.setBackground(Color.red);
        txtExit.setForeground(Color.red);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        txtExit.setBackground(Color.white);
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void TxtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUserMousePressed
        if (TxtUser.getText().equals("Ingresa tu nombre")) {
            TxtUser.setText("");
            TxtUser.setForeground(Color.black);
        }
        if (TxtEdad.getText().equals("")) {
            TxtEdad.setText("Ingresa tu edad");
            TxtEdad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtUserMousePressed

    private void TxtEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEdadMousePressed
        if (TxtEdad.getText().equals("Ingresa tu edad")) {
            TxtEdad.setText("");
            TxtEdad.setForeground(Color.black);
        }
        if (TxtUser.getText().isEmpty()) {
            TxtUser.setText("Ingresa tu nombre");
            TxtUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtEdadMousePressed

    private void BtnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseEntered

        BtnIngresar.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BtnIngresarMouseEntered

    private void BtnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseExited
        
        BtnIngresar.setForeground(Color.white);
    }//GEN-LAST:event_BtnIngresarMouseExited

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        Home FHome = new Home();
        if(TxtUser.getText().equalsIgnoreCase("Ingresa tu nombre") || TxtUser.getText().equalsIgnoreCase("") || TxtEdad.getText().equalsIgnoreCase("Ingresa tu edad") || TxtEdad.getText().equalsIgnoreCase("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa los datos correspondientes por favor.", "Datos vacios", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }//if(TxtEdad.getText() != "Ingresa tu edad" || TxtEdad.getText() != ""){
            //javax.swing.JOptionPane.showMessageDialog(this, "Ingresa los datos correspondientes por favor.", "Datos vacios", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        //}
        else{
        FHome.name(TxtUser.getText());
        boolean hombre = RBtnHombre.isSelected();
        boolean mujer = RBtnMujer.isSelected();
        if(hombre){
            FHome.sexo("Sexo: Masculino");
        }else if(mujer){
            FHome.sexo("Sexo: Femenino");
        }else{
            FHome.sexo("Sexo: Anonimo");
        }
        int edad = Integer.parseInt(TxtEdad.getText());
        if(edad <= 90 && edad >= 11){
            FHome.edad(TxtEdad.getText());
            FHome.setVisible(true);
            this.setVisible(false);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Lo siento tu edad parece irreal y/o eres menor de 11 años.", "Edad erronea", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void TxtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUserFocusLost
        if (TxtEdad.getText().equals("Ingresa tu edad")) {
            TxtEdad.setText("");
            TxtEdad.setForeground(Color.black);
        }
        if (TxtUser.getText().isEmpty()) {
            TxtUser.setText("Ingresa tu nombre");
            TxtUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtUserFocusLost

    private void TxtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUserFocusGained
        if (TxtUser.getText().equals("Ingresa tu nombre")) {
            TxtUser.setText("");
            TxtUser.setForeground(Color.black);
        }
        if (TxtEdad.getText().equals("")) {
            TxtEdad.setText("Ingresa tu edad");
            TxtEdad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtUserFocusGained

    private void TxtEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtEdadFocusGained
        if (TxtEdad.getText().equals("Ingresa tu edad")) {
            TxtEdad.setText("");
            TxtEdad.setForeground(Color.black);
        }
        if (TxtUser.getText().isEmpty()) {
            TxtUser.setText("Ingresa tu nombre");
            TxtUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtEdadFocusGained

    private void TxtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtEdadFocusLost
        if (TxtUser.getText().equals("")) {
            TxtUser.setText("Ingresa tu nombre");
            TxtUser.setForeground(Color.black);
        }
        if (TxtEdad.getText().equals("")) {
            TxtEdad.setText("Ingresa tu edad");
            TxtEdad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtEdadFocusLost

    private void TxtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEdadKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_TxtEdadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //JFrame.setDefaultLookAndFeelDecorated(true);
                String estilo = javax.swing.UIManager.getSystemLookAndFeelClassName();
                
                try {
                    javax.swing.UIManager.setLookAndFeel(estilo);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.ButtonGroup GrupoSexo;
    private javax.swing.JLabel LblEdad;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblRelaciones;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JRadioButton RBtnHombre;
    private javax.swing.JRadioButton RBtnMujer;
    private javax.swing.JRadioButton RBtnNo;
    private javax.swing.JRadioButton RBtnSi;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.ButtonGroup mesesrel;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables

}
