/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pruebaproyectofinal;

import java.awt.Color;

/**
 *
 * @author nightlyhorny
 */
public class Login extends javax.swing.JFrame {
    int xMouse, yMouse;

    /** Creates new form Inicio */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSexo = new javax.swing.ButtonGroup();
        mesesrel = new javax.swing.ButtonGroup();
        Bg = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtFieldUser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TFEdad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        BtnIngresar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        header = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        Bg.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Biblioteca de ETS");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 228, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/icons8-hospital-100.png"))); // NOI18N
        Bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Biblioteca de ETS");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("by Ian Roberto Tejada Reyes (NightlyHorny)");
        Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/city.png"))); // NOI18N
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("esta no sera compartida con nadie.");
        Bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Por favor ingresa la siguiente informacion para continuar");
        Bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");
        Bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel9.setText("INICIAR SESIÓN");
        Bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        TxtFieldUser.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        TxtFieldUser.setForeground(new java.awt.Color(153, 153, 153));
        TxtFieldUser.setText("Ingresa tu nombre");
        TxtFieldUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldUserMousePressed(evt);
            }
        });
        TxtFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldUserActionPerformed(evt);
            }
        });
        Bg.add(TxtFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        jLabel10.setText("Has tenido relaciones los ultimos meses:");
        Bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        TFEdad.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        TFEdad.setForeground(new java.awt.Color(153, 153, 153));
        TFEdad.setText("Ingresa tu edad");
        TFEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFEdadMousePressed(evt);
            }
        });
        TFEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEdadActionPerformed(evt);
            }
        });
        Bg.add(TFEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        jLabel11.setText("Edad:");
        Bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        GrupoSexo.add(jRadioButton1);
        jRadioButton1.setText("Hombre");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        Bg.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        GrupoSexo.add(jRadioButton2);
        jRadioButton2.setText("Mujer");
        Bg.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        BtnIngresar.setBackground(new java.awt.Color(0, 102, 153));
        BtnIngresar.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseExited(evt);
            }
        });
        Bg.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 80, 30));

        jLabel12.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        jLabel12.setText("Sexo:");
        Bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        mesesrel.add(jRadioButton3);
        jRadioButton3.setText("No");
        Bg.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        mesesrel.add(jRadioButton4);
        jRadioButton4.setText("Si");
        Bg.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldUserActionPerformed

            
          
        
    }//GEN-LAST:event_TxtFieldUserActionPerformed

    private void TFEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEdadActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        txtExit.setBackground(Color.red);
        txtExit.setForeground(Color.red);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        txtExit.setBackground(Color.white);
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void TxtFieldUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldUserMousePressed
        if (TxtFieldUser.getText().equals("Ingresa tu nombre")) {
            TxtFieldUser.setText("");
            TxtFieldUser.setForeground(Color.black);
        }
        if (TFEdad.getText().equals("")) {
            TFEdad.setText("Ingresa tu edad");
            TFEdad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtFieldUserMousePressed

    private void TFEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFEdadMousePressed
        if (TFEdad.getText().equals("Ingresa tu edad")) {
            TFEdad.setText("");
            TFEdad.setForeground(Color.black);
        }
        if (TxtFieldUser.getText().isEmpty()) {
            TxtFieldUser.setText("Ingresa tu nombre");
            TxtFieldUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFEdadMousePressed

    private void BtnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseEntered

        BtnIngresar.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BtnIngresarMouseEntered

    private void BtnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseExited
        
        BtnIngresar.setForeground(Color.white);
    }//GEN-LAST:event_BtnIngresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.ButtonGroup GrupoSexo;
    private javax.swing.JTextField TFEdad;
    private javax.swing.JTextField TxtFieldUser;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.ButtonGroup mesesrel;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables

}
